#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TRAVEL_SPEED 1
#define SPEED_OF_LIGHT 5
#define WAVE_SPAN 2
#define MAX_TOWER_MESSAGE_LENGTH 20
#define MAX_SPACESHIP_MESSAGE_LENGTH 9
#define MAX_SPACESHIP_MEMORY_LENGTH 8
#define MAX_SPACESHIP_VISION_RANGE 1

#endif // CONSTANTS_H
